### ISSUE TITLE
I get error when start to train

### ISSUE THREAD

**Issue by kikirizki** [ebadawy/voice_conversion#12]
Hi thank you for your great work. I am sorry I get problem when try to train. When I run this command :
 `python train.py --model_name [name of the model] --dataset [path/to/dataset]` 
 I got this error :
`NameError: name 'transfer_combos' is not defined`

**Comment by ebadawy** [comment]
yea.. seems that this variable is being called and it is not defined. you can disable `plot_interval` by setting it to `-1` and it should work. will submit a fix to it. thanks for pointing out to this error.

**Comment by RussellSB** [comment]
Thanks for bringing this to our attention @kikirizki - we are working on resolving this bug. It should be resolved soon

**Comment by Scx123** [comment]
There seem some variables not to be  defined in train.py about train_global(), `losses = train_local(i, epoch, batch, pair[src_id], pair[trg_id], losses)`.

**Comment by RussellSB** [comment]
> There seem some variables not to be defined in train.py about train_global(), `losses = train_local(i, epoch, batch, pair[src_id], pair[trg_id], losses)`.

Thanks @Scx123 , it seems like a line went missing during pushing and merging. Just updated it now

**Comment by rohitgupta3** [comment]
Hi @RussellSB, thanks for this fix (e.g. `i` is no longer causing an exception), but I still get a `NameError` for `pair` on the same line that @Scx123 referenced. Can you take a look? Thanks very much.

**Comment by RussellSB** [comment]
> Hi @RussellSB, thanks for this fix (e.g. `i` is no longer causing an exception), but I still get a `NameError` for `pair` on the same line that @Scx123 referenced. Can you take a look? Thanks very much.

Thanks for bringing this to our attention! Apologies for the overlook around this area. This should be fixed now. Let us know if any other issues persist.
